version: '3'

services: 
  
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql/db/data:/var/lib/mysql
      - ./mysql/db/init:/docker-entrypoint-initdb.d/:ro
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network
      
  node:
    build: 
      context: ./node
    container_name: node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 30s docker-entrypoint.sh
    command: node server.js
    networks: 
      - node-network
    tty: true
    depends_on: 
       - db

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    networks: 
      - node-network
    tty: true
    depends_on: 
       - node
    ports: 
      - "8080:80"
  
networks: 
  node-network:
    driver: bridge      